name: SayNews
favicon: null
layout_spectrum: 0.10301242885179818
typography_spectrum: 0.37545264000073075
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2567044112365693
  lightness: 0.3792036916129291
  saturation: 0.9775217978749424
  rhythmicContrast: 0.583382231881842
purpose: []
